name: Stable Diffusion Minecraft Skin Generator

on:
  workflow_dispatch:
    inputs:
      prompt:
        description: 'Your prompt for the skin generation'
        required: true
      sd_model:
        description: 'Stable Diffusion Model Version (2/xl, xl understands better prompts)'
        required: true
        default: 'xl'
      num_inference_steps:
        description: 'Number of inference steps (more integer value = better but longer process)'
        required: true
        default: '50'
      guidance_scale:
        description: 'Guidance scale (how much the output adheres to the prompt)'
        required: true
        default: '7.5'
      model_precision_type:
        description: 'Model precision type (fp16 for faster or fp32 for more precision)'
        required: true
        default: 'fp16'
      seed:
        description: 'Seed (an integer or 0 for random)'
        required: true
        default: '0'
      filename:
        description: 'Output filename with .png extension'
        required: true
        default: 'generated_skin.png'
      model_3d:
        description: 'See the skin also as a 3D Model? (y/n)'
        required: true
        default: 'n'
      verbose:
        description: 'Produce Verbose (detailed) Output? (y/n)'
        required: true
        default: 'n'

jobs:
  generate-skin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r Scripts/requirements_no_ui.txt
          pip install -r Scripts/requirements_ui.txt
          pip install accelerate transformers diffusers minepi numpy torch scipy pygltflib 

      - name: Generate skin
        run: |
          prompt="{{{ inputs.prompt }}}"
          sd_model="{{{ inputs.sd_model }}}"
          num_inference_steps="{{{ inputs.num_inference_steps }}}"
          guidance_scale="{{{ inputs.guidance_scale }}}"
          model_precision_type="{{{ inputs.model_precision_type }}}"
          seed="{{{ inputs.seed }}}"
          filename="{{{ inputs.filename }}}"
          model_3d="{{{ inputs.model_3d }}}"
          verbose="{{{ inputs.verbose }}}"

          if [[ "$sd_model" == "2" ]]; then
            sd_model_version="minecraft-skins"
          else
            sd_model_version="minecraft-skins-sdxl"
          fi

          if [[ "$verbose" == "y" ]]; then
            verbose_flag="--verbose"
          else
            verbose_flag=""
          fi

          if [[ "$model_3d" == "y" ]]; then
            model_3d_flag="--model_3d"
          else
            model_3d_flag=""
          fi

          python Scripts/"$sd_model_version".py "$prompt" "$num_inference_steps" "$guidance_scale" "$model_precision_type" "$seed" "$filename" "$model_3d_flag" "$verbose_flag"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          tag_name: 'v${{ runner.os }}-skin-${{ github.run_number }}'
          name: 'Generated Skin - ${{ runner.os }} - ${{ github.run_number }}'
          body: 'Generated skin using Stable Diffusion.'
          prerelease: true
          files: ${{ runner.workspace }}/${filename} 

      - name: Cleanup
        run: |
          deactivate
          rm -rf .venv
