name: Stable Diffusion Minecraft Skin Generator

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate_skin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt

      - name: Generate Skin
        run: |
          source .venv/bin/activate
          python Scripts/Run_Inference_UI.py --prompt "A Minecraft skin of a cool astronaut" --sd_model xl --num_inference_steps 50 --guidance_scale 7.5 --model_precision_type fp16 --seed 42 --filename output.png --model_3d y --verbose y
          deactivate

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: generated-skin
          path: output.png
