name: Stable Diffusion Minecraft Skin Generator

on:
  workflow_dispatch:

jobs:
  generate-skin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m venv venv_no_ui
          source venv_no_ui/bin/activate
          pip install -r Scripts/requirements_no_ui.txt

      - name: Run script
        run: |
          source venv_no_ui/bin/activate
          python Scripts/minecraft-skins.py "${{ secrets.PROMPT }}" 50 7.5 fp16 0 "output.png" --model_3d --verbose
          deactivate

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: generated-skin
          path: output.png

  generate-skin-sdxl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m venv venv_no_ui
          source venv_no_ui/bin/activate
          pip install -r Scripts/requirements_no_ui.txt

      - name: Run script
        run: |
          source venv_no_ui/bin/activate
          python Scripts/minecraft-skins-sdxl.py "${{ secrets.PROMPT }}" 50 7.5 fp16 0 "output.png" --model_3d --verbose
          deactivate

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: generated-skin
          path: output.png

  generate-skin-ui:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m venv venv_ui
          source venv_ui/bin/activate
          pip install -r Scripts/requirements_ui.txt

      - name: Run script
        run: |
          source venv_ui/bin/activate
          python Scripts/Run_Inference_UI.py
          deactivate
