name: Stable Diffusion Minecraft Skin Generation

on:
  workflow_dispatch:

jobs:
  generate-skin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m venv venv_no_ui
          source venv_no_ui/bin/activate
          pip install -r Scripts/requirements_no_ui.txt

      - name: Run inference
        run: |
          python Scripts/minecraft-skins.py \
            "$prompt" \
            "$num_inference_steps" \
            "$guidance_scale" \
            "$model_precision_type" \
            "$seed" \
            "$filename" \
            "$model_3d_flag" \
            "$verbose_flag"

      - name: Create release draft
        uses: softprops/action-gh-release@v2
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ filename }}
          asset_name: ${{ filename }}
          asset_content_type: image/png
          tag: 'v1.0.0'
          name: 'Stable Diffusion Minecraft Skin'
          body: 'Generated using Stable Diffusion'
          draft: true
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: 'v1.0.0'
          release_name: 'Stable Diffusion Minecraft Skin'
          body: 'Generated using Stable Diffusion'
          draft: true

      - name: Deactivate virtual environment
        run: deactivate
